### ISSUE TITLE
Only trigger onclick handlers if enabled.

### ISSUE THREAD

**Issue by dbatiste** [BrightspaceUI/button#115]
If an onclick event handler is wired up to the component (ex. `d2l-button`), it still gets run when the `disabled` attribute is present.

**Comment by dlockhart** [comment]
I wonder if the onclick code is also running twice, once on the underlying button and once on the `<d2l-button>`? The underlying `<button>` element will have the correct behaviour, so I wonder if it's just a matter of listening to the event on the button and then preventing default on it to stop the bubble up to `d2l-button`?

**Comment by dlockhart** [comment]
We should also consider putting the fix in `d2l-button-behavior`.

**Comment by dbatiste** [comment]
Yeah I think that's probably it.  Might just need to check `Polymer.dom(e).rootTarget`.

**Comment by dlockhart** [comment]
Closing as this repo is archived and this issue has been resolved.
