### ISSUE TITLE
RTL styles incorrect when using Polymer 1

### ISSUE THREAD

**Issue by emil-furniss** [BrightspaceUI/button#121]
RTL styles incorrectly since v4.4.1 (#118) on Polymer 1.
v4.4.1+
![rtl-button-4 4 1](https://user-images.githubusercontent.com/32819802/42539642-90d52d76-8450-11e8-881d-2f38a7032335.PNG)
v4.4.0
![rtl-button-4 4 0](https://user-images.githubusercontent.com/32819802/42539647-960f8304-8450-11e8-8f08-f8f327797d2f.PNG)

**Comment by dlockhart** [comment]
Some fixes were made in `4.4.1`... @margaree would you be able to have a look?

**Comment by margaree** [comment]
yup I'll take a look
