### ISSUE TITLE
d2l-button-icon ignores the passed in icon size tier

### ISSUE THREAD

**Issue by jwong-d2l** [BrightspaceUI/button#130]
d2l-button-icon currently forces the size of button icons to be .9rem (see https://github.com/BrightspaceUI/button/pull/124)

We need bigger button-icons, but design wants to keep this limit in to maintain design consistency.
>They don’t want this to use button-icon at all, in fact it actually supposed to be more like the icons in the main navbar within Brightspace (the course selector, notifications, gear, etc.).
>This all falls under an “immersive nav” design pattern that the designers still aren’t sure about yet. So his recommendation (and I agree) is that we don’t standardize around a component just yet until they’ve had time to solidify the pattern.

According to Lockhart:
>fix it at version 4 of icons for now, I’ll bring this up at our next designer checkpoint and escalate it.

**Comment by svanherk** [comment]
Hey @jwong-d2l, has the `d2l-navigation-button-notification-icon.html` (https://github.com/BrightspaceUI/navigation/blob/master/d2l-navigation-button-notification-icon.html) been working for you?  Can this issue be closed?

**Comment by jwong-d2l** [comment]
Yes!  Thanks so much!
